name: repository_mirroring

on: push

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: mirror
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:EpitechPGE1-2025/G-DOP-200-PAR-2-1-chocolatine-52.git
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
